[tools]
gradle = "7.0.2"
java = "corretto-11"
python = "3.11"

[tasks.test]
description = "Run tests"
run = "./.venv/bin/pytest"

[tasks.typecheck]
description = "Run mypy type checker"
run = "./.venv/bin/mypy src/"
