repositories:
  - id: spring-petclinic-cloud
    name: Spring PetClinic Cloud
    url: https://github.com/spring-petclinic/spring-petclinic-cloud.git
    path: workspace/spring-petclinic-cloud

products:
  - id: petclinic
    name: Spring PetClinic Microservices
    repository_ids:
      - spring-petclinic-cloud