"""SBOM tools for use with the SBOMAgent.

Each tool is decorated with ``@tool`` so it can be bound directly to a
LangChain/LangGraph ReAct agent.

SBOM generation is delegated to the ``cdxgen`` CLI, which must be installed.
See https://cyclonedx.github.io/cdxgen for installation instructions.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

from langchain_core.tools import tool

from src.core.logging import get_logger
from src.core.process import run_command

logger = get_logger(__name__)


def create_sbom_tools(project_path: str) -> list:
    """Create SBOM tools pinned to *project_path*.

    Tools operate within the configured project directory so the LLM cannot
    accidentally run cdxgen against the wrong path.

    Args:
        project_path: Absolute or relative path to the project directory.

    Returns:
        List of LangChain tools ready to be bound to an agent.
    """
    _project_path = str(Path(project_path).resolve())
    _default_sbom = str(Path(_project_path) / "sbom.json")

    @tool
    def generate_sbom(
        output_path: Annotated[
            str,
            "Output path for the SBOM file. Defaults to sbom.cdx.json inside the project directory.",
        ] = "",
    ) -> str:
        """Generate a CycloneDX SBOM for the project using ``cdxgen``.

        Runs ``cdxgen -o <output_path> <project_path>`` and writes the SBOM as
        JSON.  The SBOM captures all detected dependencies and their metadata.
        """
        out = output_path or _default_sbom
        logger.debug("generate_sbom: project={!r} output={!r}", _project_path, out)
        run_command("cdxgen", "-o", out, _project_path)
        return f"SBOM generated at '{out}'."

    @tool
    def get_sbom_metadata(
        sbom_path: Annotated[
            str,
            "Path to the SBOM JSON file. Defaults to sbom.cdx.json inside the project directory.",
        ] = "",
    ) -> str:
        """Return metadata from the SBOM (project name, version, generation tool, timestamp).

        Reads the ``metadata`` section of a CycloneDX JSON SBOM and formats it
        as a human-readable summary.
        """
        path = sbom_path or _default_sbom
        logger.debug("get_sbom_metadata: path={!r}", path)
        data = json.loads(Path(path).read_text(encoding="utf-8"))

        meta = data.get("metadata", {})
        comp = meta.get("component", {})
        tools_used = [
            t.get("name", "?") for t in meta.get("tools", {}).get("components", [])
        ]

        lines = [
            f"BOM format   : {data.get('bomFormat', 'N/A')} {data.get('specVersion', '')}",
            f"Serial number: {data.get('serialNumber', 'N/A')}",
            f"Timestamp    : {meta.get('timestamp', 'N/A')}",
            f"Project name : {comp.get('name', 'N/A')}",
            f"Version      : {comp.get('version', 'N/A')}",
            f"Type         : {comp.get('type', 'N/A')}",
            f"Generated by : {', '.join(tools_used) if tools_used else 'N/A'}",
            f"Components   : {len(data.get('components', []))}",
        ]
        return "\n".join(lines)

    @tool
    def list_components(
        sbom_path: Annotated[
            str,
            "Path to the SBOM JSON file. Defaults to sbom.cdx.json inside the project directory.",
        ] = "",
        limit: Annotated[
            int,
            "Maximum number of components to return (0 = all). Useful for large SBOMs.",
        ] = 50,
    ) -> str:
        """List components (dependencies) recorded in the SBOM.

        Returns name, version, type, and package URL for each dependency.
        When *limit* is non-zero only the first N entries are shown along with
        a count of remaining items.
        """
        path = sbom_path or _default_sbom
        logger.debug("list_components: path={!r} limit={}", path, limit)
        data = json.loads(Path(path).read_text(encoding="utf-8"))

        components = data.get("components", [])
        if not components:
            return "No components found in SBOM."

        total = len(components)
        subset = components if limit <= 0 else components[:limit]

        lines: list[str] = []
        for c in subset:
            name = c.get("name", "?")
            version = c.get("version", "N/A")
            ctype = c.get("type", "?")
            purl = c.get("purl", "")
            line = f"- [{ctype}] {name}@{version}"
            if purl:
                line += f"  ({purl})"
            lines.append(line)

        summary = f"Showing {len(subset)} of {total} components:\n" + "\n".join(lines)
        if limit > 0 and total > limit:
            summary += f"\n... and {total - limit} more (increase limit to see all)."
        return summary

    @tool
    def search_component(
        query: Annotated[str, "Component name or keyword to search for (case-insensitive)"],
        sbom_path: Annotated[
            str,
            "Path to the SBOM JSON file. Defaults to sbom.cdx.json inside the project directory.",
        ] = "",
    ) -> str:
        """Search for components in the SBOM whose name contains *query*.

        Performs a case-insensitive substring match against component names and
        returns full details (name, version, type, purl, licenses) for matches.
        """
        path = sbom_path or _default_sbom
        logger.debug("search_component: query={!r} path={!r}", query, path)
        data = json.loads(Path(path).read_text(encoding="utf-8"))

        needle = query.lower()
        matches = [c for c in data.get("components", []) if needle in c.get("name", "").lower()]

        if not matches:
            return f"No components matching '{query}' found in SBOM."

        lines: list[str] = [f"Found {len(matches)} component(s) matching '{query}':"]
        for c in matches:
            name = c.get("name", "?")
            version = c.get("version", "N/A")
            ctype = c.get("type", "?")
            purl = c.get("purl", "")
            licenses = [
                lic.get("license", {}).get("id") or lic.get("license", {}).get("name", "?")
                for lic in c.get("licenses", [])
            ]
            lines.append(f"\nName   : {name}")
            lines.append(f"Version: {version}")
            lines.append(f"Type   : {ctype}")
            if purl:
                lines.append(f"PURL   : {purl}")
            if licenses:
                lines.append(f"License: {', '.join(filter(None, licenses))}")
        return "\n".join(lines)

    return [generate_sbom, get_sbom_metadata, list_components, search_component]
